services:
  - type: web
    name: futbolpro
    plan: free
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn paginacamisetas.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: postgresql://postgres.qkqjrvzwzjtqaakxieqc:S3rk0s3453%2A%2A@aws-1-eu-central-1.pooler.supabase.com:5432/postgres
      - key: SUPABASE_PROJECT_REF
        value: qkqjrvzwzjtqaakxieqc
      - key: SUPABASE_STORAGE_ACCESS_KEY
        value: eadb2cd3254762891665d415e445efff
      - key: SUPABASE_STORAGE_SECRET_KEY
        value: a4398344f6937a2657f1d8fd0c5fceb872885a7969b09992baea1af725ceb135
      - key: SUPABASE_STORAGE_BUCKET
        value: camisetas
