# Generated by Django 6.0.4 on 2026-06-07 16:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales del cliente')),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('confirmado', '✅ Confirmado'), ('pagado', '💰 Pagado'), ('enviado', '📦 Enviado'), ('entregado', '🎉 Entregado')], default='pendiente', max_length=20)),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('notas_admin', models.TextField(blank=True, help_text='Notas internas (solo visibles para el admin)')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('url_base', models.URLField(help_text='URL base del proveedor en Yupoo (ej: https://194939.x.yupoo.com)', max_length=500)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, help_text='Notas internas sobre este proveedor')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('tipo', models.CharField(choices=[('liga', '⚽ Liga de Club'), ('seleccion', '🏳️ Selección Nacional'), ('retro', '🕰️ Retro / Clásica'), ('version', '👕 Versión (Jugador/Fan)'), ('kids', '👶 Niños'), ('otro', '📦 Otro')], default='liga', max_length=20)),
                ('orden', models.IntegerField(default=0)),
                ('icono', models.CharField(blank=True, default='⚽', help_text='Emoji decorativo', max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Categoría padre (dejar vacío para categoría raíz)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='tienda.categoria')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre limpio y profesional', max_length=400)),
                ('nombre_original', models.CharField(blank=True, help_text='Nombre original del scraping (para trazabilidad)', max_length=400)),
                ('slug', models.SlugField(max_length=450, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción SEO-friendly')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='Precio en EUR (opcional)', max_digits=8, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen principal (se sube a AWS S3)', null=True, upload_to='productos/')),
                ('imagen_url_original', models.URLField(blank=True, help_text='URL original de la imagen en Yupoo (fallback)', max_length=700)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('destacado', models.BooleanField(default=False, help_text='Mostrar en sección destacados')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='tienda.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('parche', models.BooleanField(default=False)),
                ('dorsal', models.BooleanField(default=False)),
                ('texto_dorsal', models.CharField(blank=True, max_length=50, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='tienda.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Línea de pedido',
                'verbose_name_plural': 'Líneas de pedido',
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/galeria/')),
                ('imagen_url', models.URLField(blank=True, max_length=700)),
                ('orden', models.IntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yupoo_album_id', models.CharField(db_index=True, help_text='ID del álbum en Yupoo para este proveedor', max_length=100)),
                ('url_album', models.URLField(blank=True, help_text='URL directa al álbum en Yupoo', max_length=700)),
                ('precio_proveedor', models.DecimalField(blank=True, decimal_places=2, help_text='Precio del proveedor (si difiere)', max_digits=8, null=True)),
                ('fecha_scraping', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_proveedor', to='tienda.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_producto', to='tienda.proveedor')),
            ],
            options={
                'verbose_name': 'Enlace Producto-Proveedor',
                'verbose_name_plural': 'Enlaces Producto-Proveedor',
                'unique_together': {('proveedor', 'yupoo_album_id')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(blank=True, related_name='productos', through='tienda.ProductoProveedor', to='tienda.proveedor'),
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('S-M', 'S-M (Niños)'), ('M-L', 'M-L (Niños)'), ('L-XL', 'L-XL (Niños)'), ('16', 'Talla 16'), ('18', 'Talla 18'), ('20', 'Talla 20'), ('22', 'Talla 22'), ('24', 'Talla 24'), ('26', 'Talla 26'), ('28', 'Talla 28')], max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('permite_dorsal', models.BooleanField(default=True, help_text='¿Se puede personalizar el dorsal?')),
                ('permite_parche', models.BooleanField(default=True, help_text='¿Se puede añadir parche?')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Variante de producto',
                'verbose_name_plural': 'Variantes de producto',
                'ordering': ['producto', 'talla'],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'categoria'], name='tienda_prod_activo_dcd120_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['slug'], name='tienda_prod_slug_646ce0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='varianteproducto',
            unique_together={('producto', 'talla')},
        ),
    ]
