# Generated by Django 6.0.4 on 2026-04-22 15:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales del cliente')),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('confirmado', '✅ Confirmado'), ('pagado', '💰 Pagado'), ('enviado', '📦 Enviado'), ('entregado', '🎉 Entregado')], default='pendiente', max_length=20)),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('notas_admin', models.TextField(blank=True, help_text='Notas internas (solo visibles para el admin)')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Camiseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_url', models.URLField(blank=True, max_length=500)),
                ('imagen_local', models.ImageField(blank=True, null=True, upload_to='camisetas/')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tallas_disponibles', models.JSONField(default=list)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('yupoo_album_id', models.CharField(blank=True, max_length=100)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camisetas', to='tienda.categoria')),
            ],
            options={
                'verbose_name': 'Camiseta',
                'verbose_name_plural': 'Camisetas',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('camiseta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.camiseta')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='tienda.pedido')),
            ],
            options={
                'verbose_name': 'Línea de pedido',
                'verbose_name_plural': 'Líneas de pedido',
            },
        ),
    ]
