# Generated by Django 6.0.4 on 2026-06-10 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('confirmado', '✅ Confirmado'), ('pagado', '💰 Pagado'), ('enviado', '📦 Enviado'), ('entregado', '🎉 Entregado')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
