# Generated by Django 6.0.4 on 2026-04-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camiseta',
            name='tipo',
            field=models.CharField(choices=[('fan', 'Fan Version'), ('player', 'Player Version'), ('retro', 'Retro')], default='fan', max_length=20),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='dorsal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='parche',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='texto_dorsal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
