# Generated by Django 6.0.4 on 2026-06-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_pedido_estado_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='token_idempotencia',
            field=models.CharField(blank=True, db_index=True, help_text='Token único para evitar duplicados en reintentos de red', max_length=100, null=True, unique=True),
        ),
    ]
