# Generated by Django 6.0.4 on 2026-04-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_camiseta_tipo_lineapedido_dorsal_lineapedido_parche_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camiseta',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='lineapedido',
            name='precio_unitario',
        ),
    ]
