# Generated by Django 6.0.4 on 2026-07-02 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_pedido_token_idempotencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('confirmado', '✅ Confirmado'), ('pagado', '💰 Pagado'), ('enviado', '📦 Enviado'), ('entregado', '🎉 Entregado'), ('cancelado', '❌ Cancelado')], db_index=True, default='pendiente', max_length=20),
        ),
    ]
