"""
Django settings for paginacamisetas project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv  # 1. Importar la librería

BASE_DIR = Path(__file__).resolve().parent.parent

# 2. DESPUÉS lo usas para cargar el .env
load_dotenv(os.path.join(BASE_DIR, '.env'))

# 3. Reemplazar la cadena de texto por os.getenv
SECRET_KEY = os.getenv('SECRET_KEY')

# También puedes hacerlo con DEBUG para mayor seguridad
DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = ['sergioa.pythonanywhere.com', 'www.sergioa.pythonanywhere.com', '127.0.0.1', 'localhost', 'futbolpro.onrender.com', '.onrender.com', '.fly.dev']

# Configuración de seguridad para producción (PythonAnywhere/Supabase)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',   # django-storages para AWS S3
    'tienda',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'paginacamisetas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'paginacamisetas.wsgi.application'


import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}

if DATABASES['default'].get('ENGINE') == 'django.db.backends.postgresql':
    DATABASES['default']['OPTIONS'] = {
        'sslmode': 'require',
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# ═══════════════════════════════════════════════════════════════════════════════
#  ARCHIVOS ESTÁTICOS — Permanecen en local / PythonAnywhere
# ═══════════════════════════════════════════════════════════════════════════════
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# ═══════════════════════════════════════════════════════════════════════════════
#  SUPABASE STORAGE (S3-compatible) — Para archivos MEDIA (imágenes de camisetas)
# ═══════════════════════════════════════════════════════════════════════════════
SUPABASE_PROJECT_REF = os.environ.get('SUPABASE_PROJECT_REF', 'qkqjrvzwzjtqaakxieqc')
SUPABASE_STORAGE_ACCESS_KEY = os.environ.get('SUPABASE_STORAGE_ACCESS_KEY')
SUPABASE_STORAGE_SECRET_KEY = os.environ.get('SUPABASE_STORAGE_SECRET_KEY')
SUPABASE_STORAGE_BUCKET = os.environ.get('SUPABASE_STORAGE_BUCKET', 'camisetas')
SUPABASE_STORAGE_REGION = os.environ.get('SUPABASE_STORAGE_REGION', 'eu-central-1')

# Endpoint S3-compatible de Supabase
SUPABASE_S3_ENDPOINT = f'https://{SUPABASE_PROJECT_REF}.supabase.co/storage/v1/s3'

# URL pública para acceder a las imágenes
SUPABASE_STORAGE_PUBLIC_URL = f'https://{SUPABASE_PROJECT_REF}.supabase.co/storage/v1/object/public/{SUPABASE_STORAGE_BUCKET}'

if SUPABASE_STORAGE_ACCESS_KEY:
    # ── Producción: Supabase Storage ──
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "access_key": SUPABASE_STORAGE_ACCESS_KEY,
                "secret_key": SUPABASE_STORAGE_SECRET_KEY,
                "bucket_name": SUPABASE_STORAGE_BUCKET,
                "region_name": SUPABASE_STORAGE_REGION,
                "endpoint_url": SUPABASE_S3_ENDPOINT,
                "querystring_auth": False,
                "file_overwrite": False,
                "custom_domain": f'{SUPABASE_PROJECT_REF}.supabase.co/storage/v1/object/public/{SUPABASE_STORAGE_BUCKET}',
                "object_parameters": {
                    "CacheControl": "max-age=86400",
                },
            },
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    MEDIA_URL = f'{SUPABASE_STORAGE_PUBLIC_URL}/'
else:
    # ── Desarrollo local: FileSystem ──
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Para que las sesiones funcionen (cesta)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
